### ISSUE TITLE
Cant resolve agora_node_ext

### ISSUE THREAD

**Issue by WildHorse19** [AgoraIO/Electron-SDK#137]
![Untitled123](https://user-images.githubusercontent.com/41179841/64757367-a4ba4100-d53a-11e9-8d20-e6cae81ae9c8.jpg)
![Untitled1](https://user-images.githubusercontent.com/41179841/64757368-a552d780-d53a-11e9-9ec4-cc0ae21ca838.jpg)

"agora-electron-sdk": "^2.9.0"

I tried to install agora electron sdk but i can see the following error (see screenshot), i tried to use quickstart boilerplate and i see same error there, you can see content of build folder on screenshot, please suggest what i can try, i also tried to do electron-rebuild with 32 arch, still same error, any advice will be highly appreciated 

THANK YOU VERY MUCH FOR YOUR HELP!

**Comment by plutoless** [comment]
if you are running under example folder. you will need to build sdk files on root folder first. as you can see, example is trying to reference sdk api at root folder instead of node_modules

**Comment by plutoless** [comment]
@WildHorse19  thank you for the suggestion. if you indeed want to set it up via pure webpack yourself, you may also take a look at [this repo](https://github.com/AgoraIO-Usecase/eEducation/tree/master/education_electron). I just personally believe it makes more sense to use our websdk if you are already using web techs like WEBRTC
