### ISSUE TITLE
在项目中引入agora-electron-sdk失败

### ISSUE THREAD

**Issue by Futureeee** [AgoraIO/Electron-SDK#151]
使用方式：npm install
版本：2.9.0
package.json:
`
"devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "electron": "4.2.8",
    "electron-builder": "^20.38.5",
    "electron-packager": "^12.1.1",
    "electron-webpack": "^2.7.4",
    "webpack": "^4.40.2"
  },
  "dependencies": {
    "agora-electron-sdk": "^2.9.0-hotfix.2",
    "electron-prompt": "^1.2.0",
    "source-map-support": "^0.5.9"
  },
  "resolutions": {
    "webpack-sources": "1.0.1"
  },
  "electronWebpack": {
    "renderer": {
      "webpackConfig": "webpack.renderer.additions.js"
    }
  },
  "agora_electron": {
    "prebuilt": true,
    "electron_version": "4.2.8"
  }
`

错误信息
`
ReferenceError: navigator is not defined
      at /Users/chencaifa/Documents/guorou_project/course_web_electron/node_modules/yuv-canvas/src/WebGLFrameSink.js:430:3
      at /Users/chencaifa/Documents/guorou_project/course_web_electron/node_modules/yuv-canvas/src/WebGLFrameSink.js:434:4
      at Object.<anonymous> (/Users/chencaifa/Documents/guorou_project/course_web_electron/node_modules/yuv-canvas/src/WebGLFrameSink.js:507:3)
      at Object.<anonymous> (/Users/chencaifa/Documents/guorou_project/course_web_electron/node_modules/yuv-canvas/src/WebGLFrameSink.js:509:3)
      at Module._compile (internal/modules/cjs/loader.js:693:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
      at Module.load (internal/modules/cjs/loader.js:602:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
      at Function.Module._load (internal/modules/cjs/loader.js:533:3)
      at Module.require (internal/modules/cjs/loader.js:640:17)
`

**Comment by plutoless** [comment]
请参考 https://github.com/AgoraIO-Community/Agora-Electron-Quickstart

**Comment by Futureeee** [comment]
> 请参考 https://github.com/AgoraIO-Community/Agora-Electron-Quickstart

已参考。依赖也基本相同，除了没有安装react相关的依赖。
因为我的项目是纯引入外部链接的，所以是在electron的index.js就引入sdk，跟示例项目在react web里面引入不一样，不知道是不是因为这个导致navigator is not defined。
特来请教。

**Comment by plutoless** [comment]
你是在浏览器console里看到的错误吗，为什么会没有navigator?

**Comment by Futureeee** [comment]
node报错，npm run dev启动不了

**Comment by Matrixbirds** [comment]
我们的sdk依赖electron的渲染进程环境，你不能再主进程里引入，这里需要在渲染进程里引入，你可以参考下我们quickstart的引入方式。你可以到这里了解到[electronjs进程的区别](https://electronjs.org/docs/tutorial/application-architecture#main-and-renderer-processes)

**Comment by Futureeee** [comment]
我的情况是两个项目分离的，electron做外壳，包着web的项目。我这种情况可以使用agora-electron-sdk吗？

**Comment by Matrixbirds** [comment]
分离就不行了。如果你的场景需要用electron sdk 我们建议用quickstart作为项目基础。套壳的话建议用[websdk](https://docs.agora.io/cn/Interactive%20Broadcast/start_live_web?platform=Web)

**Comment by Futureeee** [comment]
懂了，谢谢。

**Comment by Futureeee** [comment]
期待可以研发一个套壳的项目也可以使用的sdk。
