### ISSUE TITLE
agora_node_ext not found

### ISSUE THREAD

**Issue by zzyundragon** [AgoraIO/Electron-SDK#187]
electron ^6.0.12
agora-electron-sdk ^2.9.0-hotfix.2

 ERROR  Failed to compile with 1 errors   
This relative module was not found:

* ../../build/Release/agora_node_ext in ./node_modules/agora-electron-sdk/js/Api/index.js

运行即报错not found，请教问题出在哪里了？？

**Comment by Matrixbirds** [comment]
麻烦提供一下平台信息。
首次集成的话推荐使用我们的quickstart https://github.com/AgoraIO-Community/Agora-Electron-Quickstart
阅读一下wiki
https://github.com/AgoraIO-Community/Agora-Electron-Quickstart/wiki/%E6%90%AD%E5%BB%BA%E6%95%99%E7%A8%8B
需要检查一下你的package.json里agora_electron部分的参数 目前我们推荐用electron的5.0.8版本

**Comment by plutoless** [comment]
@zzyundragon 你是在自己的项目里集成吗？需要配置一下webpack

**Comment by zzyundragon** [comment]
@plutoless 配置了external， 'agora-electron-sdk': 'commonjs2 agora-electron-sdk'
@Matrixbirds 将electron降低到了5.0.8 现在可以了 但是同事的机器上每次安装依赖包都会很慢甚至不成功。。很担心部署到服务器时依赖装不下来

**Comment by zzyundragon** [comment]
> @zzyundragon 你是在自己的项目里集成吗？需要配置一下webpack

是在自己的项目中集成的，参照的 https://github.com/AgoraIO-Community/Agora-Electron-Quickstart

**Comment by plutoless** [comment]
@zzyundragon 可以参考这里加速依赖包下载 https://blog.yasking.org/a/zh-install-electron-development.html

**Comment by zzyundragon** [comment]
@plutoless 好的我试试 感谢大佬

**Comment by chenyupeng99** [comment]
This relative module was not found:

* ../build/Release/agora_node_ext in ./node_modules/.store/agora-electron-sdk@4.5.0/node_modules/agora-electron-sdk/js/Utils.js
