### ISSUE TITLE
调用setLiveTranscoding修改分辨率时报错

### ISSUE THREAD

**Issue by ClaytonPetrosian** [AgoraIO/Electron-SDK#260]
![image](https://user-images.githubusercontent.com/17127196/72485378-8777e500-3842-11ea-81c0-b06255068b06.png)

升级agora-electron-sdk为2.9.0-hotfix.2版本的话，就会和devtool断开
![image](https://user-images.githubusercontent.com/17127196/72485398-9363a700-3842-11ea-93e1-09ba957fa21f.png)

**Comment by RoJoHub** [comment]
这种情况请查看文档.这是由于传参未按格式传入引起的
