### ISSUE TITLE
Fail to build electron-sdk with electron 7 

### ISSUE THREAD

**Issue by squalle0nhart** [AgoraIO/Electron-SDK#269]
I alway got this error when try to build agora electron sdk with electron 7. It can be install with electron 5.x with prebuild: false. 

My package.json: 
`"agora_electron": {
    "electron_version": "7.1.4",
    "prebuilt": false,
    "platform": "darwin"
  }`

Error message: 

> ./agora_node_ext/agora_rtc_engine.cpp:3422:26: error: no matching member function for call to 'Set'
                    dev->Set(v8::String::NewFromUtf8(args.GetIsolate(), "deviceid", NewStringType::kInternalized).ToLocalChecked(), di);

> fatal error: too many errors emitted, stopping now [-ferror-limit=]
41 warnings and 20 errors generated.
make: *** [Release/obj.target/agora_node_ext/agora_node_ext/agora_rtc_engine.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/user/user/demo/node_modules/agora-electron-sdk
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

Currently agora electron sdk only support electron 5.x?

**Comment by plutoless** [comment]
@squalle0nhart we have supported 7.x in dev/2.9.1 branch and dev/2.9.0.101 branch

**Comment by squalle0nhart** [comment]
> we have supported 7.x in dev/2.9.1 branch and dev/2.9.0.101 branch

Thank you so much! I've try with dev/2.9.1 branch but get another error 

`In file included from ../common/video_source_ipc.cpp:11:
../common/video_source_ipc.h:21:10: fatal error: 'IAgoraRtcEngine.h' file not found
#include "IAgoraRtcEngine.h"
         ^~~~~~~~~~~~~~~~~~~
2 warnings and 1 error generated.
make: *** [Release/obj.target/VideoSource/common/video_source_ipc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"`

**Comment by plutoless** [comment]
the error means sdk is missing.
in latest branch we try to prevent uploading sdk binary into code repository.
try running npm run sync:lib before building.

**Comment by plutoless** [comment]
in fact you can also using prebuilt 7.1.2 version with npm version 2.9.1-beta.5, if you are installing our sdk as depencency

**Comment by squalle0nhart** [comment]
> the error means sdk is missing.
> in latest branch we try to prevent uploading sdk binary into code repository.
> try running npm run sync:lib before building.

Build done! Thank you very much.
