### ISSUE TITLE
请问这个SDK支持64bit的Electron吗？

### ISSUE THREAD

**Issue by little-tomorrow** [AgoraIO/Electron-SDK#280]

**Comment by plutoless** [comment]
windows暂时不支持

**Comment by plutoless** [comment]
64位的机器可以跑32位的electron的，这也是我们一般推荐的做法，这边是有什么原因需要64位吗？

**Comment by DavidSongzw** [comment]
@plutoless 支持自己构建64位的吗？如果支持的话？有文档说明吗？

**Comment by plutoless** [comment]
![image](https://user-images.githubusercontent.com/471561/98464631-34bb4f80-21ff-11eb-834b-8138765e3e30.png)
在这个属性里指定: arch: "x64"，我们会下载64位的预编译包，不过这样的话打包和electron必须用x64，最后也只能在64位上的机器跑
