### ISSUE TITLE
SDK构建建议

### ISSUE THREAD

**Issue by smildlzj** [AgoraIO/Electron-SDK#284]
`// check platform
  if (platform === 'win32') {
    command.push(`--arch=ia32 --msvs_version=${msvsVersion}`)
  }

  // check runtime
  if (runtime === 'electron') {
    command.push(`--target=${electronVersion} --dist-url=https://atom.io/download/electron`)
  }`

1 没必要指定target arch disturl等，一般做electron的，都会在npmrc里面已经指定了，node-grp也会自动读取这些变量，现在需要人为设置过多变量，还有写死了disturl，我们这种内网有加速镜像的。

2 没必要直接做download逻辑，直接用node-pre-gyp就可以自动实现整套流程，也不需要人为赋值prebuilt

**Comment by plutoless** [comment]
第一点我会参考一下，第二点主要是编译需要对应的编译工具，尤其是windows我知道的很多windows开发没有VS，有的话也可能版本不对或者出现各种问题，所以目前我们会尽可能预编译好提供，如果您这边觉得开发环境完全没问题，prebuilt设置一下就好了

**Comment by smildlzj** [comment]
> 第一点我会参考一下，第二点主要是编译需要对应的编译工具，尤其是windows我知道的很多windows开发没有VS，有的话也可能版本不对或者出现各种问题，所以目前我们会尽可能预编译好提供，如果您这边觉得开发环境完全没问题，prebuilt设置一下就好了

第二点其实，无论现有的形式，还是采用node-pre-gyp，并不有影响（最后还是得实际执行，node-gyp编译），只不过使用node-pre-gyp更符合node的风格。起码我们可以自定义内部mirror。而且对于你们开发人员来说，省掉处理很多逻辑。

**Comment by plutoless** [comment]
@smildlzj 我懂你意思了，node-pre-gyp我之前确实没考虑到，我了解一下，如果没问题我们会考虑接下去全线切换成node-pre-gyp
