### ISSUE TITLE
electron 8版本构建不通过

### ISSUE THREAD

**Issue by Smoking** [AgoraIO/Electron-SDK#287]
错误信息如下：
2>..\agora_node_ext\agora_rtc_engine.cpp(3394): error C2661: “v8::Object::Set”: 没有重载函数接受 2 个参数

其实就是node版本不兼容造成的问题，同一个函数v8 函数在不同的node版本之间需要的参数不一样，可以使用 nan  模块去兼容这种C++插件跨node版本问题

**Comment by plutoless** [comment]
已经用了，可以看一下2.9.0.102分支，我试过是可以支持的
