### ISSUE TITLE
mac 平台 getAudioPlaybackDevices 返回的播放设备列表不包含虚拟声卡,但是 window 可以.

### ISSUE THREAD

**Issue by Tomyail** [AgoraIO/Electron-SDK#34]
mac 上面装了Soundflower, 但是 getAudioPlaybackDevices 并不能获取到这个设备.
但是相同的方法在 window 上面能正确返回(window 安装的是e2e Soft VAudio).

![image](https://user-images.githubusercontent.com/350722/52550940-38952480-2e15-11e9-89f2-1ca54c15ef72.png)

**Comment by plutoless** [comment]
@Tomyail 我试了下mac的native sdk也可以复现，所以应该是mac sdk的问题，这个问题内部已经建了issue了，更新后会同步到这里。

**Comment by plutoless** [comment]
@Tomyail 这边和sdk同事沟通了一下，是有什么特别的理由需要获取到虚拟声卡吗？你们这边客户会使用不同的虚拟声卡吗，预安装虚拟声卡+hardcode声卡设备名的方式是否可以满足你们这边的场景？
目前了解下来mac这边基于实现理由屏蔽了虚拟声卡

**Comment by Tomyail** [comment]
如果获取不到虚拟声卡, 那么就拿不到虚拟声卡的 deviceid.  私有接口`che.audio.set_default_playback_device:xxx` 需要传入 deviceid 才生效.

**Comment by Tomyail** [comment]
你们提供的补丁已经解决. https://github.com/Tomyail/Electron-SDK/commit/7f7701eb67925cb6c4343a9c750541fb4256894b
