### ISSUE TITLE
确认下用虚拟声卡作为 loopback 的基本流程

### ISSUE THREAD

**Issue by Tomyail** [AgoraIO/Electron-SDK#35]
之前你们给过一个虚拟声卡定制版本,用来解决回音问题,我们切换到官方版本后出现了一些问题,所以想再次确认下 api 调用流程.

1. 通过 getAudioPlaybackDevices 判断虚拟声卡已经在设备列表中.
2. 调用che.audio.set_default_playback_device:xxx, 这个私有接口把对应的虚拟声卡设置成系统默认声卡.
3. 调用 enableLoopbackRecording,并确保第二个参数是虚拟声卡的名字.

目前 mac 上面遇到了遇到的第一个问题已经报了 https://github.com/AgoraIO/Electron-SDK/issues/34, window 端通过上述了流程学生端确实能听到老师端分享的桌面声音,但是老师端自己听不到桌面声音了.求指导...

**Comment by plutoless** [comment]
这个流程应该没有问题，如果本地听不到的话，确认下老师本地的播放音量是否正常。
同时确认下这个设置是否正确
![image](https://user-images.githubusercontent.com/471561/52553120-87df5300-2e1d-11e9-968e-f61cb0ff9d96.png)

**Comment by Tomyail** [comment]
@plutoless 这个操作没有作用,去掉私有接口`che.audio.set_default_playback_device:xxx` 的调用,老师和学生都能听到老师本地的声音,但是学生端会出现回音(就是学生说一句话之后,老师把学生的声音又传给学生了)

**Comment by plutoless** [comment]
我们再调查一下

**Comment by plutoless** [comment]
@Tomyail sdk组已经判断这个确实是mac上的bug，你们这边对这个接口的需求急吗？正式版会在2.4.0包括，如果急的话我们可以帮你申请出特殊版，细节可以在客户支持群里谈，可能要先和您这边的BD发起一下申请

**Comment by plutoless** [comment]
@Tomyail  上面这个问题指的是 https://github.com/AgoraIO/Electron-SDK/issues/34

**Comment by Tomyail** [comment]
window 相同的虚拟声卡安装多次会出现此问题,卸载多余的声卡后问题解决
