### ISSUE TITLE
Electron 8 support

### ISSUE THREAD

**Issue by dsa** [AgoraIO/Electron-SDK#355]
I successfully built off the development branch:
`npm install --save https://github.com/AgoraIO/Electron-SDK.git#dev/2.9.0.102`

I run into these problems when running the app. If I include this in my webpack config:
```
config.externals = { 
    "agora-electron-sdk": "commonjs2 agora-electron-sdk" 
}
```
I get this error:
> Cannot find module '.../node_modules/agora-electron-sdk/js/AgoraSdk.js'. Please verify that the package.json has a valid "main" entry

If I **remove** the above lines from my webpack config, then I get:
> Uncaught SyntaxError: Unexpected token '!' in main.chunk.js line 493:
rtcEngine = new !(function webpackMissingModule() { var e = new Error("Cannot find module 'agora-electron-sdk'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())();

Any ideas?

**Comment by plutoless** [comment]
is there any chance you can try 7.1.2 out?

**Comment by dsa** [comment]
I downgraded electron and the prebuilt version works. I was able to get the dev branch to work, but it involved copying the JS folder from a manual build to the node_modules folder and fixing the agora_node_ext path to point to agora_node_ext.node

Is there a timeline on when a prebuilt version for Electron 8 will be available? Or is there a way to resolve the issues I mention above on a missing JS folder and path issue?

**Comment by plutoless** [comment]
@dsa  i will try to solve it in next 3.0.1 release. also i will fix the non-prebuilt issue. currently some files are missing so you will see errors if you turn off prebuilt option. The release should be ready by end of may.

**Comment by dsa** [comment]
@plutoless is there an ETA on the fix for missing files in the non-prebuilt version?

**Comment by plutoless** [comment]
it will be ready by end of may. it's on my schedule

**Comment by dsa** [comment]
Thanks @plutoless
