### ISSUE TITLE
设置加入会议初始化不打开本地摄像头的bug

### ISSUE THREAD

**Issue by fjb040911** [AgoraIO/Electron-SDK#36]
文档中对于 enableVideo() 这个方法的说明是：如果 joinChannel 前不调用enableVideo() 此方法，则不打开本地摄像头，以语音的形式参加。
实际前面没执行enableVideo的情况下只要调用了 joinChannel 就会立即打开摄像头，跟文档描述不符

**Comment by plutoless** [comment]
你这边如果希望加入频道后不要打开摄像头，可以在加入频道前主动调用一下disableVideo，这个看起来更像文档的问题，我和文档同事确认一下

**Comment by fjb040911** [comment]
OK,非常感谢
