### ISSUE TITLE
使用npm安装完成后报错：This relative module was not found

### ISSUE THREAD

**Issue by FJHou** [AgoraIO/Electron-SDK#364]
![image](https://user-images.githubusercontent.com/22517598/82637950-713ac500-9c38-11ea-966d-e861ff0636eb.png)

使用npm安装完成后，出现个错误。找不到解决办法。使用官方示例（Agora-Electron-Vue）不报错。

"agora-electron-sdk": "^3.0.0-build.473",
 "electron": "^5.0.13",

**Comment by plutoless** [comment]
请参考官方示例的webpack配一下externals或者配一下node-loader
https://github.com/AgoraIO-Community/Agora-Electron-Quickstart/blob/master/Agora-Electron-React/webpack.config.js
