### ISSUE TITLE
api setLiveTranscoding failed !

### ISSUE THREAD

**Issue by just-wq** [AgoraIO/Electron-SDK#368]
控制台保错：
api setLiveTranscoding failed. this is an error
              thrown by c++ addon layer. it often means sth is
              going wrong with this function call and it refused
              to do what is asked. kindly check your parameter types
              to see if it matches properly.
setLIveTranscoding的参数是：
 {
          width: 640,
          height: 480,
          videoBitrate: 500,
          videoFrameRate: 15,
          lowLatency: true,
          videoGop: 30,
          videoCodecProfile: 77,
          backgroundColor: 0xc0c0c0,
          userCount: 1,
          audioSampleRate: 1,
          audioChannels: 1,
          transcodingUsers: [
            {
              uid,
              x: 0,
              y: 0,
              width: 320,
              height: 240,
              zOrder: 1,
              alpha: 1,
              audioChannel: 1,
            },
          ],
          watermark: {
            url: '',
            x: 0,
            y: 0,
            width: 0,
            height: 0,
          },
        };

（uid为joinedChannel事件的传参）

**Comment by RoJoHub** [comment]
请查看入参格式是否按照文档填写
