### ISSUE TITLE
Electron: Loading non-context-aware native module in renderer

### ISSUE THREAD

**Issue by dagouzhi** [AgoraIO/Electron-SDK#369]
[https://github.com/electron/electron/issues/18397](https://github.com/electron/electron/issues/18397) 

```
(node:32519) Electron: Loading non-context-aware native module in renderer: '/Users/xxx/code/coding/xxxx/node_modules/agora-electron-sdk/build/Release/agora_node_ext.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
```

- electron: 9.0.0
- mac: 10.15.4

**Comment by plutoless** [comment]
turn off reuseRenderProcess and this error should be gone.

**Comment by gentlecoder** [comment]
> turn off reuseRenderProcess and this error should be gone.

where can i turn off this

**Comment by gentlecoder** [comment]
how can i fix this in electron 12 ?

https://www.electronjs.org/docs/breaking-changes#default-changed-loading-non-context-aware-native-modules-in-the-renderer-process-is-disabled-by-default
