### ISSUE TITLE
Mac上屏幕共享，720p1视频区域和鼠标位置的错误

### ISSUE THREAD

**Issue by fjb040911** [AgoraIO/Electron-SDK#37]
Mac版本为macOS Mojave 10.14(其他版本上还未测试)
当把屏幕共享的分辨率设置为50（720p1）时候，被截取的区域不对，上下丢失。且鼠标的位置不正确。
被共享的程序窗口改变大小时候，画面无法自动调整成匹配的。同时建议提供相应的事件监听，监听被共享的窗口“改变大小”，“关闭”，“最小化”等操作事件

**Comment by plutoless** [comment]
可以提供一下具体的截图吗？
屏幕共享的分辨率设置需要在videosource加入频道并且调用startScreenShare才有效

**Comment by fjb040911** [comment]
现在提供更加明确的场景。
屏幕共享时候，如果我设置了720p(1280*720) ，代码如下
`this.rtcEngine.videoSourceSetVideoProfile(50, false);`
假如被共享窗口的尺寸宽/高正好是4/3 的比例，例如1280 * 720 。那么一切都是刚刚的好，如下图所示。
![12809](https://user-images.githubusercontent.com/8717555/54088500-890e8c00-4399-11e9-81d7-d5a722ac17ad.png)

假如被共享窗口的尺寸宽/高小于 4/3,例如 1280*1000，那么高度会被切掉280（上下各140），如下图所示：
![tb](https://user-images.githubusercontent.com/8717555/54088399-c7577b80-4398-11e9-9520-cbbf119823be.png)
假如被共享窗口的尺寸宽/高大于4/3，例如1500*720,那么左右两边宽度会被切掉220（左右各110），如下图所示
![lr](https://user-images.githubusercontent.com/8717555/54088449-23ba9b00-4399-11e9-8e89-fd7ce49bb228.png)

**Comment by fjb040911** [comment]
我尝试一种办法可以解决这个问题：
先调用以下方法把被共享窗口的宽高传入
`this.rtcEngine.setVideoEncoderConfiguration({width:this.srcId.width,height:this.srcId.height,fps:10,bitrate:1200})`
再调用以下方法开始共享屏幕：
`this.rtcEngine.startScreenCapture2(windowId, captureFreq, rect, bitrate);`

**Comment by plutoless** [comment]
嗯，因为发送会按照设定的profile进行，所以你描述的是设计行为，如果你知道怎么获取窗口宽高，那这样做确实是可以的

**Comment by fjb040911** [comment]
> 我尝试一种办法可以解决这个问题：
> 先调用以下方法把被共享窗口的宽高传入
> `this.rtcEngine.setVideoEncoderConfiguration({width:this.srcId.width,height:this.srcId.height,fps:10,bitrate:1200})`
> 再调用以下方法开始共享屏幕：
> `this.rtcEngine.startScreenCapture2(windowId, captureFreq, rect, bitrate);`

不好意思，以上的做法如果同时存在发送摄像头视频的场景下不建议使用。
`setVideoEncoderConfiguration` 这个方法看起来是设置全局的，会把正在进行的视频给弄坏，本地渲染有概率会一片绿。
所以目前看起来 屏幕共享时候`videoSourceSetVideoProfile`方法是把共享源强行截取成一定的比例，我认为应该是补充黑边成一定比例比较合理

**Comment by plutoless** [comment]
非合法分辨率导致视频变绿的问题我们已经在修复了
目前我们选择的策略是放大 + 截取，黑边对于部分客户来说可能不能接受

**Comment by fjb040911** [comment]
> 非合法分辨率导致视频变绿的问题我们已经在修复了
> 目前我们选择的策略是放大 + 截取，黑边对于部分客户来说可能不能接受

非常感谢您的回复。
放大+截取，在屏幕共享的场景下并不合适，选中共享某个窗口但出来的画面有丢失部分边缘，跟用户预期会不一致。所以能否加一个策略配置也好？

**Comment by plutoless** [comment]
我标记为enhancement了，会考虑添加，时间上暂时不确定

**Comment by fjb040911** [comment]
另外，有没考虑加入以下三个功能的支持：
1，多屏幕的支持。目前如果有外接多个屏幕的情况下，调用 getScreenWindowsInfo()  返回的屏幕缩略图是把多个屏幕图像拼接一起的。共享的时候仅会共享第一个屏幕。
2，选择开始共享某个窗口的时候，自动让这个窗口获取焦点前置（类似Chrome的插件调用共享时候的效果）
3，类似Chrome的共享插件那样对共享窗口resize后共享的视频区域自适应。目前官方建议：窗口有resize的时候调用 videoSourceUpdateScreenCaptureRegion 方法重新截取区域，但由于这里无法监听某个windowId的resize或者最小化事件，所以目前我的做法只能通过不断调用getScreenWindowsInfo来轮询更新。

**Comment by plutoless** [comment]
这些需求其实更像是对于我们windows/mac native sdk的需求:) 我把这些需求提给我们产品了，如果后续有支持会在这里更新

**Comment by plutoless** [comment]
即将发布的2.4.0应该解决了这个问题

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Electron-SDK/commit/1c2dc3b7b24014ba525c0edbf37ffa7d0c96ecb4

**Comment by plutoless** [comment]
已修复
