### ISSUE TITLE
Mac系统，打包后，调用joinChannel会白屏并且devTool从断开

### ISSUE THREAD

**Issue by shaweigo** [AgoraIO/Electron-SDK#378]
在Mac系统下（10.15.5）打包，启动打包后的App。App会出现白屏并且devTool断开。
调查了一下，发现是在调用joinChannel的时候有问题并且没有任何崩溃输出。
我尝试将在代码中将joinChannel注释掉，在initialize执行之后断点，然后手动在console执行joinChannel函数，也会出现devTool断开的情况，并且代码无法执行，页没有任何错误输出。

**Comment by jagzmz** [comment]
> Package under Mac system (10.15.5) and start the packaged App. The App will have a white screen and devTool will disconnect.
> I investigated and found that there was a problem when calling joinChannel and there was no crash output.
> I try to comment out the joinChannel in the code, breakpoint after the initialize is executed, and then manually execute the joinChannel function in the console, the devTool will be disconnected, and the code cannot be executed, and there is no error output on the page.

I am having the same issue!

**Comment by cecilpeng** [comment]
https://rtcdeveloper.com/t/topic/17698/26

可以从terminal打开

**Comment by RoJoHub** [comment]
这种情况考虑 native 崩溃.  如果可以麻烦提供
控制台->崩溃报告中的 log

![image](https://user-images.githubusercontent.com/15648309/141892268-cb4795aa-a91f-450c-86dd-a6419dbe71d5.png)

**Comment by zhixinpeng** [comment]
我的系统是10.14.6 也遇到这个问题，我在 12.2 里面不会有这个问题。已经申请了麦克风和视频的权限了。
