### ISSUE TITLE
事件audiodevicestatechanged 和 videodevicestatechanged不工作

### ISSUE THREAD

**Issue by fjb040911** [AgoraIO/Electron-SDK#39]
摄像头和麦克风设备的插拔，这两个事件都不执行

**Comment by plutoless** [comment]
摄像头的设备变化事件不工作是已知问题，我们还在修复
音频设备的变化事件应该是有的

**Comment by 9oelM** [comment]
I'm trying on MacOS 10.15.7 with electron version 9.0.0. I can tell for sure that `audioDeviceStateChanged` seems to be not working. I tested it multiple times..

**Comment by 9oelM** [comment]
Turns out `audioDeviceStateChanged` only gets triggered while you are `join`ed to a channel... otherwise, it is not going to trigger that.
