### ISSUE TITLE
Electron进行屏幕共享，Mac平台正常，Windows平台无法收到videoSourceJoinedSuccess事件通知

### ISSUE THREAD

**Issue by Macrow** [AgoraIO/Electron-SDK#393]
开发平台是Mac，完成开发，在Mac环境下，一切正常，可以收到videoSourceJoinedSuccess，并可以正常进行屏幕共享，但是打包在Windows下，无法收到videoSourceJoinedSuccess事件。

Electron Agora SDK 版本是7.1.2

请问一下，这种情况如何检查问题出在哪里？

**Comment by plutoless** [comment]
这边使用的分支是？

**Comment by Macrow** [comment]
我用的是latest，electron用v7.1.2
```
agora-electron-sdk-3.0.0-build.661
```

今天再次测试，突然可以登入了，谢谢解答，我后续再关注，看看还有无此类问题。
