### ISSUE TITLE
本地视图镜像问题

### ISSUE THREAD

**Issue by Macrow** [AgoraIO/Electron-SDK#394]
按照官方文档，可以通过```setLocalVideoMirrorMode```（在setupLocalVideo前调用，返回值是0，说明调用成功）来设置本地视图的镜像模式，但是我调用了该方法，实际上摄像头在本地还是左右镜像的，远端查看视频是正常的。

麻烦请问，Electron的SDK这个方法有作用吗？

**Comment by plutoless** [comment]
这个接口目前可能确实有些问题，可以先用CSS transform替代一下

**Comment by Macrow** [comment]
用CSS确实可以暂时解决这个问题，谢谢了！
```css
transform: 'rotateY(180deg)'
```
