### ISSUE TITLE
Electron版本是否有摄像头放大缩小的功能

### ISSUE THREAD

**Issue by Macrow** [AgoraIO/Electron-SDK#396]
Agora在移动端有缩放镜头的接口```setCameraZoomFactor```，麻烦问一下，Electron版本有类似的功能吗？

**Comment by plutoless** [comment]
您好，没有的，目前zoom功能只适用于移动端，PC大多数摄像头也没有zoom功能的，如果需要支持带zoom功能的摄像头，可以考虑用自采集
