### ISSUE TITLE
关于v3版本的使用

### ISSUE THREAD

**Issue by Macrow** [AgoraIO/Electron-SDK#397]
我看到changelog里面写了
```
3.0.1-beta.1 (June 23rd, 2020)

🏠 Internal

3.0.1 SDK upgrade
support multi render
support electron 9.0.0
```

但是我没有找到怎么使用的具体说明，能简单说一下吗，我们想把Electron升级到9大版本。

另外，prebuild有没有最新的版本？

**Comment by Macrow** [comment]
补充一下，我用lastest安装prebuild版本

看到安装的是```3.0.0-build.661```版本，这个是可以直接用Electron9了吗？

**Comment by plutoless** [comment]
应该3.0.1之后才支持electron 9，使用方法是在package.json里的agora_electron属性里配置，配置方法可以参考 https://github.com/AgoraIO-Community/Agora-Electron-Quickstart

**Comment by Macrow** [comment]
prebuild好像最高只提供7.1.2，能否后续提供支持v9版本？

**Comment by plutoless** [comment]
@Macrow 试下3.0.1-beta.2，应该支持9.0.0的
