### ISSUE TITLE
[问]出于什么考虑不用desktopCapturer？

### ISSUE THREAD

**Issue by betterTry** [AgoraIO/Electron-SDK#398]
请问出于什么考虑不适用electron的desktopCapturer呢？
性能？跨平台复用？需求无法满足？UI？
请指教

**Comment by plutoless** [comment]
如果用destopCapturer如何获取分享流的数据源并传到底层C++ SDK呢？

**Comment by plutoless** [comment]
如果用destopCapturer如何获取分享流的数据源并传到底层C++ SDK呢？

**Comment by Zaynex** [comment]
> 如果用destopCapturer如何获取分享流的数据源并传到底层C++ SDK呢？

我的理解electron 屏幕捕捉的流应该也是类似webrtc 的数据格式，agora 是否提供类似的接口把流直接传到 sdk 里，这样外部可以订阅。

**Comment by betterTry** [comment]
> 如果用destopCapturer如何获取分享流的数据源并传到底层C++ SDK呢？

所以是因为需要对AEC,抗丢包等做处理，必须要dll支持，这个原因吗？

**Comment by plutoless** [comment]
@Zaynex webrtc在浏览器环境里是无法拿到视频的原始数据的，只能拿到封装对象，分享也是通过sourceId的

**Comment by plutoless** [comment]
@betterTry 一方面是性能上如果从JS采集再传入C++会非常差，然后也是因为我上面说的目前应该没有办法拿到视频的裸数据
