### ISSUE TITLE
electron 8 还不支持

### ISSUE THREAD

**Issue by yurnery** [AgoraIO/Electron-SDK#400]
electron version: 
8.2.1

项目中使用 electron8.2.1, 还是无法使用electron SDK, prebuild里最高只支持了7.1.2

**Comment by plutoless** [comment]
@yurnery 3.0.1-beta.2应该支持了9.0.0，这边一定要用8.2.1吗？也可以clone sdk自己编的

**Comment by yurnery** [comment]
@plutoless 好的, 感谢, 现在我把 SDK 升到 9 了, 有空试下
