### ISSUE TITLE
run Electron_SDK example appear this error

### ISSUE THREAD

**Issue by xdhc304** [AgoraIO/Electron-SDK#401]
ERROR in   Error: Child compilation failed:
    Module build failed (from ./node_modules/html-loader/dist/cjs.js):
    ValidationError: Invalid options object. HTML Loader has been initialized usin  g an options object that does not match the API schema.
     - options has an unknown property 'url'. These properties are valid:
       object { preprocessor?, attributes?, minimize?, esModule? }

    - validate.js:96 validate
      [example]/[html-loader]/[schema-utils]/dist/validate.js:96:11

    - ValidationError: Invalid options object. HTML Loader has been initialized us    ing an options object that does not match the API schema.

    - - options has an unknown property 'url'. These properties are valid:

    - object { preprocessor?, attributes?, minimize?, esModule? }

    - compiler.js:79
      [example]/[html-webpack-plugin]/lib/compiler.js:79:16

    - Compiler.js:343
      [example]/[webpack]/lib/Compiler.js:343:11

    - Compiler.js:681
      [example]/[webpack]/lib/Compiler.js:681:15

    - Hook.js:154 AsyncSeriesHook.lazyCompileHook
      [example]/[tapable]/lib/Hook.js:154:20

    - Compiler.js:678
      [example]/[webpack]/lib/Compiler.js:678:31

    - Hook.js:154 AsyncSeriesHook.lazyCompileHook
      [example]/[tapable]/lib/Hook.js:154:20

    - Compilation.js:1423
      [example]/[webpack]/lib/Compilation.js:1423:35

    - Hook.js:154 AsyncSeriesHook.lazyCompileHook
      [example]/[tapable]/lib/Hook.js:154:20

    - Compilation.js:1414
      [example]/[webpack]/lib/Compilation.js:1414:32

    - Hook.js:154 AsyncSeriesHook.lazyCompileHook
      [example]/[tapable]/lib/Hook.js:154:20

    - Compilation.js:1409
      [example]/[webpack]/lib/Compilation.js:1409:36

**Comment by plutoless** [comment]
looks like this is caused by html-loader version. try adjusting the version or if you need a more straight-forward example for electron sdk, take a look at this https://github.com/AgoraIO-Community/Agora-Electron-Quickstart
