### ISSUE TITLE
dev/3.1.0分支 package.json 入口错误

### ISSUE THREAD

**Issue by yurnery** [AgoraIO/Electron-SDK#402]
package.json 中指定文件入口是 `js/AgoraSdk.js`, 但实际上打包出来的文件夹是 `build`文件夹, 应该改为`build/AgoraSdk.js`

**Comment by zhangtao1104** [comment]
electron sdk build 产物分成两部分。

第一部分是 build 文件夹下的 二进制文件。

第二部分是 js 文件夹下的 js api 接口文件，所以这个是没有问题的。

**Comment by yurnery** [comment]
我直接 添加这个分支到项目中, 发现并没有 js 文件夹, 报错入口文件找不到, 我改为 build 目录下的就好了
![image](https://user-images.githubusercontent.com/16872556/90856685-150d4b80-e3b5-11ea-97d1-8cb38886a26a.png)

**Comment by zhangtao1104** [comment]
npm run build:ts  编译下 ts 文件，就能生成 js 接口文件。

**Comment by yurnery** [comment]
好的, 看到了. 
这个项目支持 ts 吗, 我改了`tsconfig.json` 也只有几个文件生成了.d.ts 声明文件

**Comment by yurnery** [comment]
@zhangtao1104 改回到 js 之后, types 生效了, 谢谢
