### ISSUE TITLE
window打包后报错agora_node_ext.node is not a valid Win32 application

### ISSUE THREAD

**Issue by LELOG** [AgoraIO/Electron-SDK#404]
![image](https://user-images.githubusercontent.com/37971363/91970396-2efe4500-ed4a-11ea-9bb3-3e91167f4e1e.png)
请问怎样解决

**Comment by plutoless** [comment]
如果用的是electron-builder打包，打包的时候arch选一下ia32

**Comment by LELOG** [comment]
非常感谢！
![image](https://user-images.githubusercontent.com/37971363/92457218-8abb4900-f1f6-11ea-923a-bbb7dd148073.png)
已解决

**Comment by wangsijie** [comment]
改成ia32后的确可以了，但是x64的不行吗，我看3.3.1的sdk上已经有支持x64，不过实际上不能用

**Comment by zhangtao1104** [comment]
"agora_electron": {
"platform": "win32",
"electron_version": "5.0.8",
"prebuilt": true,
"arch": "x64"
},

platform 为 win32 代表 windows， darwin 代表 macOS,  arch 为 x86 下载 32 位，x64 为 64 位。

electron_version 代表想要下载的 electron 版本。



@wangsijie 按照这个参数配置表进行切换就行。

**Comment by denglouhen** [comment]
我不是很懂啊，我正常npm install之后，npm run dist:win64 打出来的包可以正常点开。npm run dist:win32打出来的包就报上面的错，到底应该怎么做啊？64位的系统不应该可以正常运行32位吗？

**Comment by denglouhen** [comment]
> "agora_electron": { "platform": "win32", "electron_version": "5.0.8", "prebuilt": true, "arch": "x64" },
> 
> platform 为 win32 代表 windows， darwin 代表 macOS, arch 为 x86 下载 32 位，x64 为 64 位。
> 
> electron_version 代表想要下载的 electron 版本。
> 
> @wangsijie 按照这个参数配置表进行切换就行。

你说切换，是指什么时候切换啊？是npm install的时候切换还是electron-builder的时候切换？

**Comment by denglouhen** [comment]
> 改成ia32后的确可以了，但是x64的不行吗，我看3.3.1的sdk上已经有支持x64，不过实际上不能用

你最后怎么解决的? 不配arch=ia32的话，打出来的包64可以用，但是win32的包不行，配了ia32，打出来的包win32可以运行，win64的还是报这个错误。
