### ISSUE TITLE
怎么编更高版本的sdk

### ISSUE THREAD

**Issue by DyncEric** [AgoraIO/Electron-SDK#407]
试了下，默认编译的都是5.0.8
请问现在需要编译最新的10.x的版本如何操作呀？

**Comment by DyncEric** [comment]
试着编译一个7.1.2，结果项目中报这个错误：
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 75. Please try re-compiling or re-installing

**Comment by plutoless** [comment]
@DyncEric 这边是怎么编的呢

**Comment by ETTTTT** [comment]
node版本：v12.16.1
electron版本: v10.1.2
agora-electron-sdk版本: 3.1.2-rc231-build.981


报一样的错误，请问怎么解决呢

```
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

**Comment by plutoless** [comment]
@ETTTTT 方便说下你运行的步骤和命令行输出吗？从错误信息看你的electron版本蛮低的，应该不是10

**Comment by ETTTTT** [comment]
确实，我之前打印出来的electron版本是全局的，因为我是用electron一个脚手架安装的，发现里面的版本是2.8


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AgoraIO/Electron-SDK"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月27日(星期天) 中午11:46
收件人:&nbsp;"AgoraIO/Electron-SDK"<Electron-SDK@noreply.github.com&gt;;
抄送:&nbsp;"闭眼呼吸ヽ微笑掩饰悲伤。"<603984518@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [AgoraIO/Electron-SDK] 怎么编更高版本的sdk (#407)





 
@ETTTTT 方便说下你运行的步骤和命令行输出吗？从错误信息看你的electron版本蛮低的，应该不是10
