### ISSUE TITLE
eEducation-Web-master 集成nodejs native c++ addon 生成的.node模块 一直调不通

### ISSUE THREAD

**Issue by varyliu** [AgoraIO/Electron-SDK#410]
hello.js 文件->
var addon = require('./build/Release/hello.node');
exports.hello = function () {
    return addon.hello();
}

home.tsx文件->
const hello = require('hello');

Label={hello.hello()}

 [@运行就报错：]  TypeError：hello.hello is not a function.

**Comment by plutoless** [comment]
可以看看addon是什么，这个hello.node是你自己编的吧

**Comment by varyliu** [comment]
您好，Qianze Zhang&nbsp; &nbsp; &nbsp; &nbsp;hello.node是我自己仿照网上写的。工程我通过网盘发给您，帮忙看下，我觉得应该是哪里配置没配对或者缺少d.ts文件导致ts转js查找没找到方法吧？
&nbsp; &nbsp; &nbsp; &nbsp;1.hello模块路径链接：https://pan.baidu.com/s/1J_lBh4b9jC9gXlAbS2jaug&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;提取码：d1j8&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;2.工程路径链接：https://pan.baidu.com/s/19MM0-VnJ3PCJ2dLDZYJ_Eg&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;提取码：tane&nbsp;
非常期待您的指点




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qianze Zhang"<notifications@github.com&gt;; 
发送时间: 2020年10月12日(星期一) 上午9:52
收件人: "AgoraIO/Electron-SDK"<Electron-SDK@noreply.github.com&gt;; 
抄送: "流年@追影"<1024763439@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AgoraIO/Electron-SDK] eEducation-Web-master 集成nodejs native c++ addon 生成的.node模块 一直调不通 (#410)





 
可以看看addon是什么，这个hello.node是你自己编的吧

**Comment by varyliu** [comment]
您好，看出哪里出问题了吗？

**Comment by plutoless** [comment]
console 有什么错误吗？

**Comment by varyliu** [comment]
react-dom.production.min.js:5058 TypeError: hello.hello is not a function
&nbsp; &nbsp; at setting_aw_card (setting-aw-card.tsx:127)
&nbsp; &nbsp; at oh (react-dom.production.min.js:3667)
&nbsp; &nbsp; at Rj (react-dom.production.min.js:6635)
&nbsp; &nbsp; at Qj (react-dom.production.min.js:6150)
&nbsp; &nbsp; at Kj (react-dom.production.min.js:6139)
&nbsp; &nbsp; at yj (react-dom.production.min.js:5880)
&nbsp; &nbsp; at eval (react-dom.production.min.js:2851)
&nbsp; &nbsp; at exports.unstable_runWithPriority (scheduler.production.min.js:309)
&nbsp; &nbsp; at cg (react-dom.production.min.js:2816)
&nbsp; &nbsp; at fg (react-dom.production.min.js:2846)
Ci @ react-dom.production.min.js:5058
Xi.c.callback @ react-dom.production.min.js:5568
Cg @ react-dom.production.min.js:3108
Ji @ react-dom.production.min.js:5182
Sj @ react-dom.production.min.js:6408
exports.unstable_runWithPriority @ scheduler.production.min.js:309
cg @ react-dom.production.min.js:2816
Jj @ react-dom.production.min.js:6204
yj @ react-dom.production.min.js:5895
(anonymous) @ react-dom.production.min.js:2851
exports.unstable_runWithPriority @ scheduler.production.min.js:309
cg @ react-dom.production.min.js:2816
fg @ react-dom.production.min.js:2846
gg @ react-dom.production.min.js:2836
Ga @ react-dom.production.min.js:7265
gd @ react-dom.production.min.js:1329
react-dom.production.min.js:2857 Uncaught TypeError: hello.hello is not a function
&nbsp; &nbsp; at setting_aw_card (setting-aw-card.tsx:127)
&nbsp; &nbsp; at oh (react-dom.production.min.js:3667)
&nbsp; &nbsp; at Rj (react-dom.production.min.js:6635)
&nbsp; &nbsp; at Qj (react-dom.production.min.js:6150)
&nbsp; &nbsp; at Kj (react-dom.production.min.js:6139)
&nbsp; &nbsp; at yj (react-dom.production.min.js:5880)
&nbsp; &nbsp; at eval (react-dom.production.min.js:2851)
&nbsp; &nbsp; at exports.unstable_runWithPriority (scheduler.production.min.js:309)
&nbsp; &nbsp; at cg (react-dom.production.min.js:2816)
&nbsp; &nbsp; at fg (react-dom.production.min.js:2846)
setting_aw_card @ setting-aw-card.tsx:127
oh @ react-dom.production.min.js:3667
Rj @ react-dom.production.min.js:6635
Qj @ react-dom.production.min.js:6150
Kj @ react-dom.production.min.js:6139
yj @ react-dom.production.min.js:5880
(anonymous) @ react-dom.production.min.js:2851
exports.unstable_runWithPriority @ scheduler.production.min.js:309
cg @ react-dom.production.min.js:2816
fg @ react-dom.production.min.js:2846
gg @ react-dom.production.min.js:2836
Ga @ react-dom.production.min.js:7265
gd @ react-dom.production.min.js:1329
react-dom.production.min.js:5058 ObjectUnsubscribedErrorImpl {message: "object unsubscribed", name: "ObjectUnsubscribedError"}message: "object unsubscribed"name: "ObjectUnsubscribedError"__proto__: Error
Ci @ react-dom.production.min.js:5058
Xi.c.callback @ react-dom.production.min.js:5568
Cg @ react-dom.production.min.js:3108
Ji @ react-dom.production.min.js:5182
Sj @ react-dom.production.min.js:6408
exports.unstable_runWithPriority @ scheduler.production.min.js:309
cg @ react-dom.production.min.js:2816
Jj @ react-dom.production.min.js:6204
yj @ react-dom.production.min.js:5895
(anonymous) @ react-dom.production.min.js:2851
exports.unstable_runWithPriority @ scheduler.production.min.js:309
cg @ react-dom.production.min.js:2816
fg @ react-dom.production.min.js:2846
gg @ react-dom.production.min.js:2836
X @ scheduler.production.min.js:203
H.port1.onmessage @ scheduler.production.min.js:94






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AgoraIO/Electron-SDK"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月15日(星期四) 中午12:40
收件人:&nbsp;"AgoraIO/Electron-SDK"<Electron-SDK@noreply.github.com&gt;;
抄送:&nbsp;"流年@追影"<1024763439@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AgoraIO/Electron-SDK] eEducation-Web-master 集成nodejs native c++ addon 生成的.node模块 一直调不通 (#410)





 
console 有什么错误吗？

**Comment by plutoless** [comment]
@varyliu 这边把你自己写的项目直接传到github上吧，百度网盘过期了
