### ISSUE TITLE
windows 支持 64 位 electron 吗？如果支持有文档吗？

### ISSUE THREAD

**Issue by DavidSongzw** [AgoraIO/Electron-SDK#413]
我有个 electron 原生包，强制依赖 64 位，如果 agora-electron-sdk 不能支持 64 位，有其他解决方案吗？

**Comment by plutoless** [comment]
支持的，您可以自己编译64位，或者在依赖我们的时候通过package.json指定arch下载win64的包

**Comment by plutoless** [comment]
您是想自己编译还是用我们预编译的版本？

**Comment by DavidSongzw** [comment]
谢谢 目前自己编译了
