### ISSUE TITLE
arch is incorrect when install on mac

### ISSUE THREAD

**Issue by anyerqi** [AgoraIO/Electron-SDK#416]
package.json
```json
  "agora_electron": {
    "electron_version": "11.1.0",
    "prebuilt": false,
    "msvs_version": "2017",
    "debug": false,
    "silent": false,
    "arch": "x64"
  }
```
when I use command on mac:
```bash
yarn add agora-electron-sdk@3.1.1-build.914
```
then print error below
```bash
Output:
[11:52:14 AM] ■ started 'install'
[11:52:14 AM] ■ switching to ia32
[11:52:14 AM] x no macos lib specified
[11:52:14 AM] x Error detected while running 'install'
[11:52:14 AM] x ------------------------------------
[11:52:14 AM] x Error: no macos lib specified
```

**Comment by plutoless** [comment]
@anyerqi try this

  "agora_electron": {
    "electron_version": "11.1.0",
    "prebuilt": false,
    "msvs_version": "2017",
    "debug": false,
    "silent": false,
    "arch": "x64",
    "lib_sdk_mac": "https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_v3_1_1_FULL.zip"
  }

you need to specify the depended native sdk to complete the compile process
