### ISSUE TITLE
[Wiki] Incorrect .npmrc example

### ISSUE THREAD

**Issue by crimx** [AgoraIO/Electron-SDK#418]
https://github.com/AgoraIO/Electron-SDK/wiki/Installation-Configuration-in-package.json

❌

```bash
// .npmrc
npm_config_agora_electron_dependent=5.0.8
npm_config_agora_electron_prebuilt=true
npm_config_agora_electron_platform=darwin
npm_config_agora_electron_msvs_version=2017
npm_config_agora_electron_debug=false
npm_config_agora_electron_silent=false
```

✅

```bash
// .npmrc
agora_electron_dependent=5.0.8
agora_electron_prebuilt=true
agora_electron_platform=darwin
agora_electron_msvs_version=2017
agora_electron_debug=false
agora_electron_silent=false
```

**Comment by plutoless** [comment]
umm are you sure?
https://johnaaronnelson.com/configure-package-json-with-npmrc-2/
reading this using npm_config prefix is a proper way to configure package.json from npmrc i believe..

**Comment by crimx** [comment]
The `npm_config_` prefix is added automatically under the hood.  With the incorrect example you will get something like 
 `npm_config_npm_config_agora_electron_dependent`.

**Comment by plutoless** [comment]
@crimx just did a quick double check. you are right! i have amended the wiki according to your suggestion. appreciate for pointing this out. :)
