### ISSUE TITLE
Release\agora_node_ext.node Node.js version 

### ISSUE THREAD

**Issue by Zaynex** [AgoraIO/Electron-SDK#42]
您好，我是通过  agora-electron-quickstart 跑的项目。在项目引入 electron-sdk 时出现了这个问题。

```
ELECTRON_ASAR.js:160 Uncaught Error: \\?\E:\ynote\Agora-Electron-Quickstart\node_modules\agora-

electron-sdk\build\Release\agora_node_ext.node is not a valid Win32 application.
\\?\E:\ynote\Agora-Electron-Quickstart\node_modules\agora-electron-sdk\build\Release\agora_node_ext.node
    at process.module.(:57928/anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722)
    at Object.module.(:57928/anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602)
    at tryModuleLoad (internal/modules/cjs/loader.js:541)
    at Function.Module._load (internal/modules/cjs/loader.js:533)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at Object.<anonymous> (E:\ynote\Agora-Electron-Quickstart\node_modules\agora-electron-sdk\js\Api\index.js:5)
    at Object.<anonymous> (E:\ynote\Agora-Electron-Quickstart\node_modules\agora-electron-sdk\js\Api\index.js:1814)
```

环境 : win10

之后尝试
```
 npm install -D --arch=ia32 electron
```
出现了新的报错

```
\E:\ynote\Agora-Electron-Quickstart\node_modules\agora-electron-sdk\build\Release\agora_node_ext.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)
```
请问如何解决？

**Comment by plutoless** [comment]
# range(1.8.3, <3.0.0) will download a prebuilt addon built with electron 1.8.3
AGORA_ELECTRON_DEPENDENT=2.0.0
# or
# range(>=3.0.0) will download a prebuilt addon built with electron 3.0.6
AGORA_ELECTRON_DEPENDENT=3.0.6
# or
# range(>= 4.0.0) will download a prebuilt addon built with electron 4.0.0
AGORA_ELECTRON_DEPENDENT=4.0.0

请按照这里的配置调整electron版本，首先electron肯定要确保安装32位的，然后electron的版本对应不同的nodejs版本，需要确保electron和预编译的c++库使用的nodejs版本一致。从你的错误来看你可能安装了4.0的electron，但下载了适用于3.0 Electron的

**Comment by Zaynex** [comment]
在官方的 https://github.com/AgoraIO-Community/Agora-Electron-Quickstart  里其实已经配置了    .npmrc。 并且设置为 
```
AGORA_ELECTRON_DEPENDENT=4.0.0
```

在下载过程中也确实更新了 electron 版本。
```
 agora-electron-sdk@2.3.3-alpha.11 install E:\ynote\Agora-Electron-Quickstart\node_modules\agora-electron-sdk
> npm run download


> agora-electron-sdk@2.3.3-alpha.11 download E:\ynote\Agora-Electron-Quickstart\node_modules\agora-electron-sdk
> node ./scripts/download.js

i  info      Package Version = 2.3.3
i  info      Platform = Windows
i  info      Dependent Electron Version = 4.0.0
i  info      Download Url = http://download.agora.io/sdk/release/Agora_RTC_Electron_SDK_for_Windows_v2_3_3_e4.zip

[ ]  pending   Downloading prebuilt C++ addon for Agora Electron SDK...

√  success   Success Download finished

> electron@4.0.8 postinstall E:\ynote\Agora-Electron-Quickstart\node_modules\electron
> node install.js

npm WARN electron-webpack-quick-start@0.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1540 packages from 850 contributors and audited 10809 packages in 159.662s
found 185 vulnerabilities (184 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

报错依然是

```
\agora-electron-sdk\build\Release\agora_node_ext.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)
```

**Comment by plutoless** [comment]
降到2.3.3-alpha.10 看看
或者改装一下electron 3.0.8

**Comment by Zaynex** [comment]
先降electron 版本，electron 3.x work 了。 感谢光速回复！

**Comment by plutoless** [comment]
alpha.11昨天发的，当时CDN有点问题部分预编译镜像是手动传的。。可能问题出在这里

**Comment by plutoless** [comment]
alpha.11昨天发的，当时CDN有点问题部分预编译镜像是手动传的。。可能问题出在这里

**Comment by plutoless** [comment]
alpha.11昨天发的，当时CDN有点问题部分预编译镜像是手动传的。。可能问题出在这里

**Comment by panxiuqing** [comment]
Electron 的版本需要在 4.0.3 及以下，4.0.4 开始 
>  Change the NODE_MODULE_VERSION to 69
[Electron 4.0.4](https://electronjs.org/releases/stable?page=2#release-notes-for-v404)

**Comment by plutoless** [comment]
@panxiuqing 多谢更新，我们昨天还查了半天CDN，我认为这个问题已经比较清晰了，这里先close了，如果有其他疑问可以reopen

**Comment by Zaynex** [comment]
@plutoless  hi，想问下 声网的sdk 的视频源数据是通过 agora_node_ext 传过来还是通过  video_source 传过来的呢？目前感觉是sdk传给了 video_source 处理，video_source 传给了 agora_node_ext. 我看了好多 deliverFrame 但不确定哪个是真正的sdk传过来的数据。 是否可以简单讲解下流程，十分感谢！

**Comment by plutoless** [comment]
AgoraVideoSourceRender，这是自渲染类
不太确定你说的video_source是哪个?

**Comment by Zaynex** [comment]
方便留个联系方式或者加我微信（xwz13750899284）么？打包的时候遇到了些问题，想请教下，谢谢

**Comment by menthays** [comment]
使用npm安装native module可以避免这个问题。
如果使用相对路径引用，需要单独配置 electron-builder 的 files 属性。
大致就是在package.json里添加额外属性，详细配置说明请参考[ electron-builder 文档](https://www.electron.build/configuration/contents.html)
```
  "build": {
    "mac": {
      "identity": null
    },
   "files": [
     "<path/to/native-modules>"
   ]
  }
```

**Comment by Zaynex** [comment]
@menthays 放到 node_modules 里执行的时候 build失败了 =  = 。但是自己本地build的时候又是好的。方案1暂时放弃了。

方案二的问题，看了官方文档还是有点不动，因为是先引入了 js。然后js文件中引入了 .node。 但是.node 又需要 dll 的文件。files 只引入  .node 路径看起来是不行的。 有这方面的经验么？求教~

**Comment by plutoless** [comment]
@Zaynex files是可以引入整个目录的，用**/*就行

**Comment by plutoless** [comment]
mac版本打包完app是可以右键显示包内容的，可以看看里面实际缺了什么，再通过files补进去

**Comment by Zaynex** [comment]
@plutoless 我打的是 windows. 我觉得问题是出现在每次打包出来的 renderer.js 文件里 读取的 global.process.dlopen('我的本地文件路径')  导致的。是不是只能通过 npm 来解决了？

**Comment by Zaynex** [comment]
@menthays  看了下yarn 的源码，想了解是不是因为遇到了 在 node_modules 里 node-gyp 失败，所以再特意在scripts 里加了 install 来避免 yarn install 完了之后触发 reBuild?

**Comment by plutoless** [comment]
@Zaynex 这样肯定是可以的，你只要把包含.node的目录放进files参数，指定在打包后拷到程序目录就可以了，你可以先加一下看看打出来的结果，然后根据位置调整一下js引用，有时候开发环境的相对.node路径和release的路径不一定一致

**Comment by menthays** [comment]
项目下有binding.gyp的npm package在安装时会自动rebuild，然后这个项目rebuild需要的环境比较复杂，尤其是windows。因此会在install的时候自动去从我们的cdn上下载提前build好的.node文件，覆盖了默认的rebuild行为

**Comment by menthays** [comment]
刚刚试了下，单纯地用files确实不行，有两个方案：
1. 使用npm安装这个sdk进行开发，参考https://github.com/AgoraIO-Community/Agora-Electron-Quickstart；
2. 将 example 父级目录（sdk所在目录）下的node_modules/ , js/ , build/ 都拷贝到 example 里的static 目录下，然后修改引用sdk的相对路径（从static），static会被electron-builder默认打包进最后的应用里

**Comment by Zaynex** [comment]
@menthays  已经按照你们的方式做了。这样子文件确实引入了，但是又发现一个坑。  
```
 The specified module could not be found.
\\?\   
in electron-asar.js
```
不知道你们有没有遇到这个问题？看了下 electron/asar repo 里 有 issue。但是一直没更新。

**Comment by Zaynex** [comment]
@menthays  已经解决了，谢谢！~

**Comment by fjb040911** [comment]
windows的打包我这边也报同样的问题。这里是如何解决的？

**Comment by fjb040911** [comment]
@plutoless 非常感谢回复。windows下用package的方式打包解决问题了，所以可以不理会我的这个问题。
builder的方式出来报的错误跟这位兄弟提的单子描述的一致。

**Comment by crossingmay** [comment]
用的 electron-react-boilerplate 脚手架，单独装了 agora-electron-sdk 后，遇到同样的问题

本地环境：
node v10.15.3
electron v4.1.3
agora-electron-sdk v2.3.3

解决办法：

安装 electron-rebuild  `yarn add electron-rebuild`

然后执行下列命令

```bash
rm -rf node_modules &&
yarn cache clean &&
yarn &&
yarn electron-rebuild &&
yarn dev
```

[ref](https://electron-react-boilerplate.js.org/docs/installation-debugging-solutions)
