### ISSUE TITLE
加入频道失败

### ISSUE THREAD

**Issue by shanzhangf123** [AgoraIO/Electron-SDK#421]
agora::rtc::NodeRtcEngine::joinChannel failed. this is an error
              thrown by c++ addon layer. it often means sth is
              going wrong with this function call and it refused
              to do what is asked. kindly check your parameter types
              to see if it matches properly.

**Comment by plutoless** [comment]
@shanzhangf123 
一般这代表你的参数类型错误，能发一下你如何调用join方法的吗？
