### ISSUE TITLE
react项目引入agora-electron-sdk报错

### ISSUE THREAD

**Issue by wuxyman** [AgoraIO/Electron-SDK#423]
webrtc已经引入过了，准备集成electron版本的，但是只是引入sdk就报错了。

Failed to compile.

./node_modules/agora-electron-sdk/js/Api/index.js
Module not found: Can't resolve '../../build/Release/agora_node_ext' in '/Users/xxx/Documents/LingoAce-LiveRoom-Web/node_modules/agora-electron-sdk/js/Api'

macOS  intel      big surgar版本

**Comment by plutoless** [comment]
.node要有对应的loader，或者webpack直接配置externals，详细可以看 https://github.com/AgoraIO-Community/Agora-Electron-Quickstart
