### ISSUE TITLE
安卓端传过来的画面有绿色蒙版

### ISSUE THREAD

**Issue by menzil** [AgoraIO/Electron-SDK#43]
版本： "agora-electron-sdk": "^2.3.2"
问题： 安卓端传过来的画面有绿色蒙版，ios端正常。
控制台输出: upload u plane 180 180 8100 error 1282和upload v plane 180 180 8100 error 1282
WebGl： INVALID_OPERATION: textImage2D:ArrayBufferView not big enough for request.

**Comment by plutoless** [comment]
该问题在最新的alpha11已经修复，麻烦更新看一下

**Comment by menzil** [comment]
谢谢
