### ISSUE TITLE
electron-builder 打包后的屏幕共享问题

### ISSUE THREAD

**Issue by fjb040911** [AgoraIO/Electron-SDK#45]
环境 ：
    "electron": "^4.1.0",
    "electron-builder": "^20.39.0",
    "electron-rebuild": "^1.8.4",
    "agora-electron-sdk": "^2.3.3-alpha.11",
描述：
1，如果是调试模式，直接运行命令 `electron .`没有问题，摄像头和屏幕共享都可以使用
2，用`electron-builder`打包出的版本，如果直接使用安装在 node_modules 中的SDK，则报错，应该是SDK没被打包进去。
3，尝试配置 `files:[ **/*  ]` 依然还是不行
4，把编译后的SDK从 node_modules 复制出来到外边目录，再让代码加载那个目录下的SDK，摄像头视频和事件都正常，但是屏幕共享功能不正常，调用 `rtcEngine.videoSourceInitialize(SDKAPPID)` 返回 -1

**Comment by plutoless** [comment]
https://github.com/AgoraIO-Community/Agora-Electron-Quickstart
你好，我这边用这个编译release版本，试了下分享屏幕没有问题，可以看看和你的有没有什么区别

**Comment by fjb040911** [comment]
设置 `"asar":false` 就可以正常调用

**Comment by Macrow** [comment]
可以打开```asar```，再增加一个```asarUnpack```，进行额外配置也可以工作。
