### ISSUE TITLE
Electron version

### ISSUE THREAD

**Issue by zjbarg** [AgoraIO/Electron-SDK#450]
What is the latest supported electron version?

# Edit
Currently I'm able to run electron 11.0.0 successfully. Is this the latest supported version?

**Comment by plutoless** [comment]
@ZaidBarghouthi we will try to keep electron support version up to date for our prebuilt but you can always compile the version yourself

**Comment by pmstani** [comment]
@plutoless please provide a prepackaged binary for Electron >= 11.0.0 - we cannot compile it ourselves and this is really critical for us.

**Comment by 9oelM** [comment]
@pmstani 
![image](https://user-images.githubusercontent.com/22465806/120784442-0ddfb480-c567-11eb-9e54-2bc8317c2dec.png)

Inspecting the source, I find that 12.0.0 is the latest supported version.

**Comment by pmstani** [comment]
@9oelM thanks, would you mind sharing your package.json settings? It seems we're not pulling the latest version of the sdk then?

**Comment by 9oelM** [comment]
I'm actually using electron version 9, but i'm sharing it anyways

MacOS:
```json
  ...other things
  "dependencies": {
      ...other things      
      "agora-electron-sdk": "3.4.2",
      ...other things      
  },
  "agora_electron": {
    "electron_version": "9.0.0",
    "prebuilt": true
  },
  ...other things
```

Windows:
```json
  ...other things
  "dependencies": {
      ...other things      
      "agora-electron-sdk": "3.4.2",
      ...other things      
  },
  "agora_electron": {
  "platform": "win32",
  "electron_version": "9.0.0",
  "prebuilt": true,
  "arch": "x64"
  },
  ...other things
```

I think you can check the version of agora-electron-sdk.

**Comment by pmstani** [comment]
Thank you, will look into it, much appreciated.
