### ISSUE TITLE
调用 startScreenCapture2 屏幕共享和停止共享 stopScreenCapture2时候的异常

### ISSUE THREAD

**Issue by fjb040911** [AgoraIO/Electron-SDK#46]
Mac上面的一个bug，（windows还没测试）。
调用这两个方法时候都会开启一下摄像头再关闭。
会有如下问题：
1，用户想做屏幕共享或者关闭屏幕共享，但弹出“调用摄像头”的权限申请窗口
2，这个动作有一定几率使得已经在进行的视频发生异常

**Comment by plutoless** [comment]
@fjb040911  是否只在release版本出现？是的话在electron-builder设置一下应用的appid等打包设置
