### ISSUE TITLE
Cannot find module in type definition file

### ISSUE THREAD

**Issue by oreshinya** [AgoraIO/Electron-SDK#504]
`tsc` outputs a error:

```
node_modules/agora-electron-sdk/types/Renderer/index.d.ts:2:30 - error TS2307: Cannot find module './SoftwareRenderer' or its corresponding type declarations.

2 import SoftwareRenderer from './SoftwareRenderer';
                               ~~~~~~~~~~~~~~~~~~~~
```

Certainly the type difinition file doesn't exist in `node_modules/agora-electron-sdk/types/Renderer/` directory.

sdk version: `3.4.1-hotfix.3`
typescript version: `4.2.4`

**Comment by RoJoHub** [comment]
Thank you for your attention, please update to the latest version to solve this problem
