### ISSUE TITLE
Create Universal Mac App(arm,x64)

### ISSUE THREAD

**Issue by silarvaibhav** [AgoraIO/Electron-SDK#505]
We are compile electron using below configuration on Mac to create universal application for arm and x64
Snippet from package.json

    "agora_electron": {
        "electron_version": "11.0.0",
        "prebuilt": false,
        "debug": false,
        "silent": false,
        "arch": "arm64", //not sure here, what should be configuration to compile for arm and x64
        "lib_sdk_mac": "https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_v3_3_1_FULL.zip"
    }

But after creating app, its not running on Mac M1, following error shows on console:

electron/js2c/asar_bundle.js:5 Uncaught Error: dlopen(/Applications/Test.app/Contents/Resources/app.asar.unpacked/node_modules/agora-electron-sdk/build/Release/agora_node_ext.node, 1): no suitable image found.  Did find:

So my question here is :  Is it possible to create universal app for agora sdk? If yes, how?

We are using 3.3.1 agora sdk

**Comment by zhangtao1104** [comment]
Maybe you can try the branch named 'dev/3.4.1' first to see if you can build the sdk which support arm64 success.

**Comment by zhangtao1104** [comment]
You can run the command named "lipo -info xxx/agora_node_ext.node" to check if your node support arm64.

**Comment by silarvaibhav** [comment]
Did following steps:
1) Checkout dev/3.4.1
2) npm install
3) npm run build:node
4) Run in terminal : lipo -info build/Release/agora_node_ext.node

Non-fat file: build/Release/agora_node_ext.node is architecture: x86_64

This is not producing arm64 .node file
I am using node v14.17.1

**Comment by silarvaibhav** [comment]
After checking out the mentioned branch, updated package json to     

"agora_electron": {
        "lib_sdk_win": "https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_v3_4_1_FULL.zip",
        "lib_sdk_mac": "https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_v3_4_1_FULL.zip",
        "arch": "arm64",
        "electron_version": "11.0.0"
    }

The error is gone now.

Thanks for the pointer.

**Comment by RoJoHub** [comment]
Thank you for your attention, the package has been verified to have arm architecture
```shell
 file /Users/jerry/Downloads/Electron-mac-3.4.2-rc.1-build.622-11.0.0/build/Release/agora_node_ext.node
/Users/jerry/Downloads/Electron-mac-3.4.2-rc.1-build.622-11.0.0/build/Release/agora_node_ext.node: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64] [arm64]
/Users/jerry/Downloads/Electron-mac-3.4.2-rc.1-build.622-11.0.0/build/Release/agora_node_ext.node (for architecture x86_64):	Mach-O 64-bit bundle x86_64
/Users/jerry/Downloads/Electron-mac-3.4.2-rc.1-build.622-11.0.0/build/Release/agora_node_ext.node (for architecture arm64):	Mach-O 64-bit bundle arm64
```
