### ISSUE TITLE
Sandboxed Mac App(arm) throws error in silicon Macbook: require is not defined

### ISSUE THREAD

**Issue by silarvaibhav** [AgoraIO/Electron-SDK#507]
electron: 11.4.8
agora-electron-sdk: 3.4.2-rc.1-build.622
platform: Silicon Macbook 2019(arm)

Error details: 
On running application, there is error in console (index):5 Uncaught ReferenceError: require is not defined which does not load agora-electron-sdk
<img width="1364" alt="Screenshot 2021-06-24 at 1 57 46 PM" src="https://user-images.githubusercontent.com/63088615/123229695-2b63c680-d4f4-11eb-97cb-463950935277.png">

On Silicon Mac, sandboxed application runs when contextIsolation flag is true. I think this is mandatory to submit in App store

But when this flag is false to make require work, sandboxed mac app crashes in Silicon Mackbook(arm)

You can check branch "example_updated" in https://github.com/silarvaibhav/Agora-Electron-Quickstart.git

package.json and main/index.js configuration is updated
window configuration in main file

>   const window = new BrowserWindow({
>     width: 1366,
>     height: 768,
>     webPreferences: {      
>       nodeIntegration: true,
>       webSecurity: false,
>       enableRemoteModule: true,
> 	    **contextIsolation : true**
>   }
>   })

Question is how to use Agora electron sdk in this case?

**Comment by RoJoHub** [comment]
please use `contextIsolation : false`

**Comment by SherrieCao** [comment]
Having a similar problem here, and `contextIsolation : false` will disable the ipc. Does anyone have a better solution?
