### ISSUE TITLE
agora-electron-sdk 升级失败

### ISSUE THREAD

**Issue by xuzeshen** [AgoraIO/Electron-SDK#514]
当“agora-electron-sdk”为“2.3.4-hotfix.4”时，是可以运行成功的，尝试升级至当前最新的版本“3.4.6-build.730”会出现“agora_rtc_engine.cpp:4730   ERR| Error :registerPlugin, :4730,  GetProcAddress "createAVFramePlugin" Failed”的报错，进而导致加载dylib失败。

**Comment by JJH0901** [comment]
请问这个问题是怎么解决的
