### ISSUE TITLE
Truly clueless versioning policy, typescript definitions and API reference

### ISSUE THREAD

**Issue by 9oelM** [AgoraIO/Electron-SDK#520]
So I noticed Agora customer support team has recently sent out this email to developers who signed up for agora.io
![image](https://user-images.githubusercontent.com/22465806/132656348-634a9936-b366-48ea-b22e-f2d268b3a3d7.png)

and so my app is on 3.4.2, and I need to upgrade to 3.4.6. I tried to look for 3.4.6 version on npmjs and I should just say that the way Agora handles agora-electron-sdk versioning is very clumsy. I'm quite confused as to 'which version' of `3.4.6` I can safely use.

![image](https://user-images.githubusercontent.com/22465806/132657099-304c5156-08b7-4d9b-8d24-748598fd0bc8.png)

Which one should I be using? You guys have marked `3.4.6-iris.730-build.1` as the `alpha` version which nobody obviously tried out but that's not the latest `3.4.6-iris.*` version available. Does that mean I should be using the newer build instead? 
![Screen Shot 2021-09-09 at 6 08 49 PM](https://user-images.githubusercontent.com/22465806/132657575-5e370e2e-cce5-47dc-8e86-924280aece8c.png)

If you are going to say 3.4.6 in your documentation like this below, please refer clearly to which version you are referring to. 
![image](https://user-images.githubusercontent.com/22465806/132657943-447dab07-29d0-4eb5-8a62-ee3c06cc28b9.png)
I do not have any knowledge about what happened in each of the versions which might or might not be stable and I just want no problems when I upgrade to the new version and migrate the code accordingly. What if this version that I was using is just for a test build?

Also, you should really work on the typescript definitions and API reference. There are just so many problems but I've got no time for that so I will just list down a few. 

1. Until 3.4.2, `AgoraRtcEngine['subscribe']` method exists in the typescript definition and [3.4.6 or 3.4.5 release notes don't mention anything about `.subscribe` getting removed](https://docs.agora.io/en/Voice/release_electron_video?platform=Electron#v346) and [I can still find `.subscribe` method from 3.4.6 documentation](https://docs.agora.io/en/Video/API%20Reference/electron/classes/agorartcengine.html#subscribe). But in `3.4.6-iris.831-build.1` (which is the version I decided to install for 3.4.6) there is no `.subscribe` in the typescript definition anymore, so I don't ever know if it really has got deprecated or is just missed out by a mistake without manually inspecting your commits on Github or contacting the customer support or posting another issue here, which is truly tiring and time wasting, given the fact that I am a paid customer of this product.
2. Many types are not just properly implemented. For example, this one:
```ts
/** VideoEncoderConfiguration */
export interface VideoEncoderConfiguration {
    dimensions: VideoDimensions;
    /**
     * The frame rate (fps) of the video.
     *
     * The default value is 15 fps.
     *
     * **Noete**:
     * We do not recommend setting this to a value greater than 30 fps.
     */
    frameRate: FRAME_RATE;
    /**
     * The minimum frame rate of the video.
     *
     * The default value is -1.
     */
    minFrameRate: number;
    /** The video encoding bitrate (Kbps).
     *
     * Set your bitrate based on the following table. If you set a bitrate
     * beyond the proper range, the SDK automatically sets it to within the
     * range.
     *
     * You can also choose one of the following bitrate options:
     * - `0`: (Recommended) The standard bitrate.
     *  - The communication(`0`) profile: the encoding bitrate equals the base
     * bitrate.
     *  - The `1` (live streaming) profile: the encoding bitrate is twice the base
     * bitrate.
     * - `-1`: The compatible bitrate.
     *  - The communication(`0`) profile: the encoding bitrate equals the base
     * bitrate.
     *  - The `1` (live streaming) profile: the encoding bitrate equals the base
     * bitrate.
     *
     * The communication(`0`) profile prioritizes smoothness, while the
     * `1` (live streaming) profile prioritizes video quality
     * (requiring a higher bitrate). We recommend setting the bitrate mode as
     * `0` to address this difference.
     *
     * The following table lists the recommended video encoder configurations.
     *
     * | Resolution             | Frame Rate (fps) | Base Bitrate (Kbps)   |
     * |------------------------|------------------|-----------------------|
     * | 160 * 120              | 15               | 65                    |
     * | 120 * 120              | 15               | 50                    |
     * | 320 * 180              | 15               | 140                   |
     * | 180 * 180              | 15               | 100                   |
     * | 240 * 180              | 15               | 120                   |
     * | 320 * 240              | 15               | 200                   |
     * | 240 * 240              | 15               | 140                   |
     * | 424 * 240              | 15               | 220                   |
     * | 640 * 360              | 15               | 400                   |
     * | 360 * 360              | 15               | 260                   |
     * | 640 * 360              | 30               | 600                   |
     * | 360 * 360              | 30               | 400                   |
     * | 480 * 360              | 15               | 320                   |
     * | 480 * 360              | 30               | 490                   |
     * | 640 * 480              | 15               | 500                   |
     * | 480 * 480              | 15               | 400                   |
     * | 640 * 480              | 30               | 750                   |
     * | 480 * 480              | 30               | 600                   |
     * | 848 * 480              | 15               | 610                   |
     * | 848 * 480              | 30               | 930                   |
     * | 640 * 480              | 10               | 400                   |
     * | 1280 * 720             | 15               | 1130                  |
     * | 1280 * 720             | 30               | 1710                  |
     * | 960 * 720              | 15               | 910                   |
     * | 960 * 720              | 30               | 1380                  |
     * | 1920 * 1080            | 15               | 2080                  |
     * | 1920 * 1080            | 30               | 3150                  |
     * | 1920 * 1080            | 60               | 4780                  |
     * | 2560 * 1440            | 30               | 4850                  |
     * | 2560 * 1440            | 60               | 6500                  |
     * | 3840 * 2160            | 30               | 6500                  |
     * | 3840 * 2160            | 60               | 6500                  |
     *
     */
    bitrate: number;
    /**
     * The minimum encoding bitrate (Kbps).
     *
     * The default value is 1 kbps.
     *
     * Using a value greater than the default value
     * forces the video encoder to output high-quality images but may cause more
     * packet loss and hence sacrifice the smoothness of the video transmission.
     * That said, unless you have special requirements for image quality,
     * Agora does not recommend changing this value.
     *
     */
    minBitrate: number;
    /**
     * The orientation mode. See {@link OrientationMode}.
     */
    orientationMode: ORIENTATION_MODE;
    /**
     * The video encoding degradation preference under limited bandwidth.
     * See {@link DegradationPreference}.
     */
    degradationPreference: DEGRADATION_PREFERENCE;
    /**
     * @since v3.0.0
     *
     * Sets the mirror mode of the published local video stream. It only affects
     * the video that the remote user sees. See {@link VideoMirrorModeType}
     *
     * @note The SDK disables the mirror mode by default.
     */
    mirrorMode: VIDEO_MIRROR_MODE_TYPE;
}

// and then it's used here
/**
     * Sets the video encoder configuration.
     *
     * Each video encoder configuration corresponds to a set of video parameters,
     * including the resolution, frame rate, bitrate, and video orientation.
     * The parameters specified in this method are the maximum values under ideal
     * network conditions. If the video engine cannot render the video using
     * the specified parameters due to poor network conditions, the parameters
     * further down the list are considered until a successful configuration is
     * found.
     *
     * If you do not set the video encoder configuration after joining the
     * channel, you can call this method before calling the {@link enableVideo}
     * method to reduce the render time of the first video frame.
     * @param {VideoEncoderConfiguration} config The local video encoder
     * configuration. See {@link VideoEncoderConfiguration}.
     * @return
     * - 0: Success.
     * - < 0: Failure.
     */
    setVideoEncoderConfiguration(config: VideoEncoderConfiguration): number;
```
It might be my misunderstanding, but why do you mention things about 'default' value, while you explicitly set the types required and do not mark them as optional (with `?`)? I already got it working without using all of the keys mentioned in the interface by just marking `@ts-ignore` above `myRtcEngine.setVideoEncoderConfiguration(...)` but I really don't want to use `@ts-ignore` on something that can actually be fixed.
3. Some methods may be necessary to be used but just have no/poor documentation at all, challenging the developer to try it out on himself by spending his own time and find out what it does just by reading the name of the function. For example, it took me a long time for me to understand the difference between [`destroyRender`](https://docs.agora.io/en/Video/API%20Reference/electron/classes/agorartcengine.html#destroyrender) and [`destroyRenderView`](https://docs.agora.io/en/Video/API%20Reference/electron/classes/agorartcengine.html#destroyrenderview) (by the way, `destroyRenderView` has also disappeared from TS definitions but still exists in 3.4.6 docs website). Everything that there is out for me to understand is just this:
![Screen Shot 2021-09-09 at 6 54 00 PM](https://user-images.githubusercontent.com/22465806/132664875-15e4a36d-5c50-4fc3-9d6c-4b18ada28ef9.png)
You could, or rather you should.. be more specific about this. While people who wrote the actual codebase may feel it easy to understand, the developers who are just trying out this sdk are likely to be clueless about this because they didn't write this code and highly likely not desiring to understand very much of the original codebase to be able to write an application based on agora-electron-sdk.
4. You have a few demo repositories and some documentations. I swear I looked into them all, but it's just so painful to learn to build a complex app out of this without trying every single thing out by myself. In the end I managed to do so, but I can't think of continuing to work like this.

I understand the nature of this repository being public. Anybody can come in and contribute. But at the same time, this is partly paid software, which means people can expect some professional degree of codes without contributing to this software. But so far the journey has been not content and I will not proceed to use it.

**Comment by 9oelM** [comment]
So I went through this tiring process of digging into details, and I found that these two versions are not properly built the way `agora-electron-sdk` has been usually built:
- `3.4.6-iris.730-build.1`
- `3.4.6-iris.831-build.1`

The difference with other properly working versions is that somehow TS build configs were changed and `ts` folder appeared and several more type definition files were created in `types` directory, which do not exist in any other versions and are not really properly implemented, which we can say that it's just a developer's mistake that wasn't cleaned out properly and is being encouraged to be used in the customer support team's email which is causing a big hassle to innocent developers like me.

other (proper) versions:

![image](https://user-images.githubusercontent.com/22465806/133354954-31de3165-c450-4403-bc69-f5a155a49f32.png)

those two problematic versions:

![image](https://user-images.githubusercontent.com/22465806/133355265-2272f484-2666-4662-b6cf-0b8a55d96123.png)


If you want to avoid any troubles at best, you will not want to use these versions. Unfortunately these are the versions that appear in the top of the options if you hit `npm i --save agora-electron-sdk@3.4.6`. Agora developers should really just get rid of this version or at least let developers know that this is not a properly working version.

**Comment by RoJoHub** [comment]
There are many customized versions on our npm, for your scene, please follow the lateat tag.
The current latest version is 3.5.0.3
![61631772448_ pic_hd](https://user-images.githubusercontent.com/15648309/133558748-af95769f-fe83-4f7c-a74e-5e43be0d709b.jpg)
