### ISSUE TITLE
目前有支持到electron版本为13.X以上的么

### ISSUE THREAD

**Issue by chenlang0311** [AgoraIO/Electron-SDK#562]
目前使用这个SDK，好像只能用5.0.8版本

**Comment by zhangtao1104** [comment]
'12.0.0','9.0.0', '7.1.2', '6.1.7', '5.0.8', '4.2.8', '3.0.6', '1.8.3'
目前支持这些版本的。

**Comment by zhangtao1104** [comment]
Electron 13 及以上版本支持，正在开发中。

**Comment by RoJoHub** [comment]
你好  electron 13+支持版本的 sdk 已经发布，
----
NPM上安装:            agora-electron-sdk@3.5.0-rc.3-iris.1027-build.1
Example(Demo):     https://github.com/AgoraIO-Community/Agora-Electron-Quickstart/tree/master/Agora-Electron-API-Example-Iris
预览版文档:		    https://docs-preprod.agora.io/cn/Video/API%20Reference/electron/v3.4.0/API/rtc_api_overview.html
