### ISSUE TITLE
引用sdk出问题

### ISSUE THREAD

**Issue by yindengli** [AgoraIO/Electron-SDK#59]
electron的这个sdk是必须要用electron-webpack吗？我把这个sdk接到我自己的一个工程中时报This relative module was not found:
* ../../build/Release/agora_node_ext in ./node_modules/agora-electron-sdk/js/Api/index.js

**Comment by plutoless** [comment]
可以不用，但要自己配置webpack 配置externals忽略.node文件，然后打包的时候自己将.node打进应用
