### ISSUE TITLE
electron 14版本不支持渲染进程加载node了，有什么其他方案吗？

### ISSUE THREAD

**Issue by Smoking** [AgoraIO/Electron-SDK#608]

**Comment by RoJoHub** [comment]
目前agora-electron-sdk 的重构版本已经推出,该版本适用于 Electron 5~16(至 laterst)版本

需要注意的是,这个版本目前为工程版本,


-------------

NPM上安装:            agora-electron-sdk@3.5.0-rc.3-iris.1123-build.1
Example(Demo):     https://github.com/AgoraIO-Community/Agora-Electron-Quickstart/tree/master/Agora-Electron-API-Example-Iris
预览版文档:		    https://docs-preprod.agora.io/cn/Video/API%20Reference/electron/v3.4.0/API/rtc_api_overview.html

**Comment by zhixinpeng** [comment]
我使用最新的sdk版本，引入到我的项目中，还是会出现无法使用node模块的问题。有这块的解决方案吗？allowRendererProcessReuse已经用不了了

**Comment by RoJoHub** [comment]
麻烦提供一下agora-electron-sdk 的版本号和具体的错误信息

**Comment by zhixinpeng** [comment]
agora_electron_sdk：3.6.0-build.111/electron: 16.0.7。
 按照示例写的 "agora_electron": {"prebuilt": true}，这样会报错Uncaught Error: Loading non-context-aware native module in renderer。
如果"agora_electron"中加入"electron_version": "16.0.7"，会提示支持的版本信息，是不包含这个版本的。

**Comment by RoJoHub** [comment]
> agora_electron_sdk：3.6.0-build.111/electron: 16.0.7。 按照示例写的 "agora_electron": {"prebuilt": true}，这样会报错Uncaught Error: Loading non-context-aware native module in renderer。 如果"agora_electron"中加入"electron_version": "16.0.7"，会提示支持的版本信息，是不包含这个版本的。

主版本目前由于架构的关系只支持到 Electron 12

重构版本的的支持到12+以上。 详细信息请参考上面的信息
