### ISSUE TITLE
什么时候能支持linux下的构建

### ISSUE THREAD

**Issue by ihipop** [AgoraIO/Electron-SDK#635]
我看MAC都支持了为什么不顺手把Linux的构建也支持了？
灵动教室把Web和electron版本在一起了，我甚至不能在在Linux下的CI构建出产物进行发布，因为agora-electron-sdk不支持Linux....

![image](https://user-images.githubusercontent.com/423077/148893350-a1436c57-6f5b-4a51-b75f-340a5af84406.png)

**Comment by RoJoHub** [comment]
agora-electron-sdk 的能力范围包括
- electron 包装层的能力
-  Native C++ SDK的能力

如果需要 linux 版本  目前 Native C++ SDK 并没有 Linux 的版本. 所以 Electron 从来也对应还未支持

非常抱歉

**Comment by ihipop** [comment]
那我如何在Linux的CI环境下构建产品呢？就是不支持了？@RoJoHub 还是说我要为win和mac单独准备一个CI环境？

**Comment by RoJoHub** [comment]
可以认为 Electron SDK 还调用了另外的 sdk,即Native C++ SDK 

然而Native C++ SDK目前没有 linux 版本。所以出不来 linux 版本的 Electron SDk

**Comment by plutoless** [comment]
@ihipop 可以的，您可以在agora-classroom-sdk的package.json中，为agora_electron提供一个额外的属性platform: "win32"，这样应该编译就能成功了
