### ISSUE TITLE
Issue while running npm install

### ISSUE THREAD

**Issue by tapasya** [AgoraIO/Electron-SDK#639]
npm ERR! code 1
npm ERR! path /<path-to-project>/node_modules/agora-electron-sdk
npm ERR! command failed
npm ERR! command sh -c just install
npm ERR! [13:16:00] ■ started 'install'
npm ERR! [13:16:00] ■ switching to ia32
npm ERR! [13:16:00] x no macos lib specified
npm ERR! [13:16:00] x Error detected while running 'install'
npm ERR! [13:16:00] x ------------------------------------
npm ERR! [13:16:00] x Error: no macos lib specified
npm ERR!     at /<path-to-project>/node_modules/agora-electron-sdk/scripts/synclib.js:190:23
npm ERR!     at new Promise (<anonymous>)

below is the config in package.json
  "agora_electron": {
      "prebuilt": false,
      "electron_version": "16.0.6",
      "platform": "darwin"
  }

**Comment by tapasya** [comment]
after adding below to agora_electron 
"lib_sdk_mac": "https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_v3_6_0_1_FULL.zip"

installation fails with below error 

1690 error Undefined symbols for architecture x86_64:
1690 error   "_main", referenced from:
1690 error      implicit entry/start for main executable
1690 error ld: symbol(s) not found for architecture x86_64
1690 error clang: error: linker command failed with exit code 1 (use -v to see invocation)
1690 error make: *** [Release/VideoSource] Error 1

**Comment by RoJoHub** [comment]
At present, the refactored version of agora-electron-sdk has been launched, which is suitable for Electron 5~16 (to laterst) version

It should be noted that this version is currently an engineering version,

Install on NPM: agora-electron-sdk@3.5.0-rc.3-iris.1123-build.1
Example(Demo): https://github.com/AgoraIO-Community/Agora-Electron-Quickstart/tree/master/Agora-Electron-API-Example-Iris
Preview Documentation: https://docs-preprod.agora.io/cn/Video/API%20Reference/electron/v3.4.0/API/rtc_api_overview.html

**Comment by tapasya** [comment]
with agora-electron-sdk@3.5.0-rc.3-iris.1123-build.1 I get the below error

ERROR in node_modules/agora-electron-sdk/types/Renderer/IRender.d.ts:3:28 - error

import { VideoFrame } from "./type";

also can you share an angular electron example ?

**Comment by plutoless** [comment]
@tapasya we would suggest you to use prebuilt: true to download a prebuilt instead of building everything from scratch yourself.

**Comment by RoJoHub** [comment]
We fixed this on the alpha release on January 12th
Please use `npm install agora-electron-sdk@3.5.0-rc.3-iris.112-build.1`
