### ISSUE TITLE
Screen sharing an external screen on Mac returns blank video

### ISSUE THREAD

**Issue by skybella** [AgoraIO/Electron-SDK#668]
tested on macOS Monterey (M1), macOS Big Sur (Intel)
electron 11.0.0
agora-electron-sdk 3.6.1-rc.2-build.222

Problem:
Code that worked with previous 3.5.1 version of the library now fails with the 3.6.X versions of the library.

Screensharing (using video source) an external display (plugged in via usb-c or hdmi) on the Mac __seems__ to succeed (no errors) but actually a blank video stream is sent. Sharing an Internal monitor & individual windows all seem to function fine, but choosing an external display results in no video.

Would love to upgrade the library but this is blocking us.

**Comment by skybella** [comment]
3.6.1-rc.1-build.122 exhibits the same bug

**Comment by RoJoHub** [comment]
Which api you used?
