### ISSUE TITLE
TypeError: agora_electron_sdk_1.default is not a constructor

### ISSUE THREAD

**Issue by wning13** [AgoraIO/Electron-SDK#757]
执行
`const rtcEngine = new AgoraRtcEngine();`
报错
`TypeError: agora_electron_sdk_1.default is not a constructor`
求助怎么解决？

electron: 12.0.0
agora-electron-sdk: 3.7.0-build.527
os: macOS Big Sur 11.6
node: v16.15.0

**Comment by plutoless** [comment]
@wning13 你好，能提供下完整的console日志吗，引入是否有什么错误

**Comment by wning13** [comment]
> @wning13 你好，能提供下完整的console日志吗，引入是否有什么错误
很不幸的是没有任何有用的日志信息
![企业微信截图_e140bff2-1f21-4784-bf29-5849147e946f](https://user-images.githubusercontent.com/7438062/172083606-6adc5151-77cf-47c4-99c2-9ed5b9d18fee.png)
![企业微信截图_56b909f8-bafb-4338-913e-d987fc1efe44](https://user-images.githubusercontent.com/7438062/172083637-e2ff28a8-872f-4ea5-9b57-803a2763635b.png)

我尝试将
`import AgoraRtcEngine from 'agora-electron-sdk';`
修改为
`import AgoraRtcEngine from 'agora-electron-sdk/js/Api';`
后报错
![企业微信截图_c0fbf694-98de-4b5b-ab96-e4f1a9a24d29](https://user-images.githubusercontent.com/7438062/172083805-dc020cb1-9de5-4467-98bc-01c1cf891772.png)

**Comment by plutoless** [comment]
@wning13 这边如果用的是webpack的话，需要把electron-sdk配置为external，不然正常无法处理.node文件

**Comment by wning13** [comment]
external已经设置过的
![企业微信截图_8dfff053-02db-475f-9186-5a99ad34d4c8](https://user-images.githubusercontent.com/7438062/172084275-834cb90c-ddea-4cb3-aed3-59a1a6d07eaa.png)

**Comment by plutoless** [comment]
@wning13 这应该是因为您配置的是agora-electron-sdk，然后您修改import方式后相当于external失效了，如果直接require的话能拿到对象吗?

**Comment by wning13** [comment]
和import一样的结果

**Comment by plutoless** [comment]
@wning13 
我指的是直接看一下require后看返回的是什么
或者这边能参考运行一下这边的quickstart吗
https://github.com/AgoraIO-Community/Agora-Electron-Quickstart

**Comment by wning13** [comment]
按照quickstart的方式将ts-loader更换为babel-loader后可以正常导入了，可能是我的webpack配置有问题，后面有时间我再确认下
