### ISSUE TITLE
在BrowserWindow中，frame置为false后，调用getScreenWindowsInfo后就拿不到这个electron的窗口信息

### ISSUE THREAD

**Issue by yindengli** [AgoraIO/Electron-SDK#76]
在BrowserWindow中，frame置为false后，调用getScreenWindowsInfo后就拿不到这个electron的窗口信息

**Comment by plutoless** [comment]
这个可能需要调查一下，可能和electron frameless窗口的实现有关，我们获取窗口列表用的应该就是系统接口
