### ISSUE TITLE
到底怎么样才能打出正常的win32的包啊？npm run dist:win32打出的包报错agora_node_ext.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by denglouhen** [AgoraIO/Electron-SDK#845]
就是下的Agora-Electron-Quickstart那个代码，我执行里面的npm run dist:win32 打出来的包，就报错：
![image](https://user-images.githubusercontent.com/26452618/186395202-8a337501-a6b1-4ea0-9975-010df4299715.png)
不应该64位的可以兼容运行32位吗？只有npm run dist:win64 打出来的包我可以正常点开？
到底应该怎么做啊？

**Comment by LichKing-2234** [comment]
请问您用的是哪个版本

**Comment by denglouhen** [comment]
> 请问您用的是哪个版本

没事了，我一直在删根目录下的node_modules，忘记删掉src里面的node_modules了。然后把改写的arch：ia32写了，重新装就好了

**Comment by denglouhen** [comment]
> 请问您用的是哪个版本

我在.npmrc里面加上了arch=ia32，然后electron版本是12.0.0，在两个package.json里都加上了
  "agora_electron": {
    "electron_version": "12.0.0",
    "prebuilt": true,
    "platform": "win32",
    "arch": "ia32"
  },
最后npm install，npm run start，成功了。打包的时候我打包dist:win32，可以允许。但是打包出来的win64，不能运行还是报那个错误。
怎么才能打出来win32和win64都可以正常啊？
啥也不改的时候win32不行，加各种arch ia32又变成了win64不行。好迷惑啊

**Comment by denglouhen** [comment]
因为我看Agora-Electron-Quickstart已经很久没活跃了，只能来这问了。window10系统，electron 12.0.0，到底怎么做才能打出win32和win64的包。代码下下来啥也不动，打出的win64包正常，win32报错。我加了一堆ia32的配置如上，win32正常，win64报错。

**Comment by plutoless** [comment]
sdk 是 x86, x86和x64的electron都可以加载
sdk 是 x64, x86的electron不能加载，x64的electron可以加载

**Comment by denglouhen** [comment]
> sdk 是 x86, x86和x64的electron都可以加载 sdk 是 x64, x86的electron不能加载，x64的electron可以加载

大佬你好，我配置了agora_electron里的"arch": "ia32"，这个应该是指定了sdk是x86的意思吧。就是出现了electron-builder --win --ia32的包可以打开，但是electron-builder --win --x64的包报错。我很费解，那个项目我拉下来什么都不改的情况下，应该是默认装的x64的sdk和x64的electron，这个时候执行electron-builder --win --ia32报错electron-builder --win --x64又是正常的。就是两种情况是反正的，我找不到一个能同时成功打包win32和win64的方法。是我哪里做错了还是这个本来就不可能？

**Comment by plutoless** [comment]
win32的包，win32和win64的electron都可以打开的
你的现象，听起来生成的是x64的包，所以x64的electron-builder可以工作，但ia32的不行
你的编译步骤能告诉我一下吗? 再详细些

**Comment by denglouhen** [comment]
> win32的包，win32和win64的electron都可以打开的 你的现象，听起来生成的是x64的包，所以x64的electron-builder可以工作，但ia32的不行 你的编译步骤能告诉我一下吗? 再详细些

1、我clone了[Agora-Electron-Quickstart](https://github.com/AgoraIO-Community/Agora-Electron-Quickstart) 这个项目master分支到我的本地，然后cd进到Agora-Electron-API-Example目录，执行yarn，之后yarn start，成功运行。然后我想试试打包的效果，我执行了package.json的script里的dist:win64，也就是yarn build && electron-builder build --publish never --win --x64。在resource目录下生成了win-unpacked文件夹，我点进去有exe，双击可以正常运行。  于是我接着又运行了yarn dist:win32，但是在win-ia32-unpacked文件夹的exe我点开，就报了is not a valid Win32那个错误。
2、有这个错误之后我就在网上到处找issue，我看都说electron要装32位的，还有什么agora_electron的配置里面要写arch：“ia32”这些。于是我就删了node_modules，然后在.npmrc里面加上了arch=ia32，在agora_electron写上了"agora_electron": {
"electron_version": "12.0.0",
"prebuilt": true,
"platform": "win32",
"arch": "ia32"
},
并且保证了electron装的是12.0.0
改了这些之后，我yarn安装，yarn start正常。我就又试了一遍yarn dist:win32和yarn dist:win64。结果这次相反，win-ia32-unpacked文件夹下的exe我点开正常了，win-unpacked文件夹下的反而又报那个错误。

我寻思项目代码我一开始原封不动下载下来，就执行yarn，yarn start，yarn dist:win64，yarn dist:win32，这几个命令，但是win32那个包就报错了。

**Comment by denglouhen** [comment]
> win32的包，win32和win64的electron都可以打开的 你的现象，听起来生成的是x64的包，所以x64的electron-builder可以工作，但ia32的不行 你的编译步骤能告诉我一下吗? 再详细些

1、我clone了[Agora-Electron-Quickstart](https://github.com/AgoraIO-Community/Agora-Electron-Quickstart) 这个项目master分支到我的本地，然后cd进到Agora-Electron-API-Example目录，执行yarn，之后yarn start，成功运行。然后我想试试打包的效果，我执行了package.json的script里的dist:win64，也就是yarn build && electron-builder build --publish never --win --x64。在resource目录下生成了win-unpacked文件夹，我点进去有exe，双击可以正常运行。  于是我接着又运行了yarn dist:win32，但是在win-ia32-unpacked文件夹的exe我点开，就报了is not a valid Win32那个错误。
2、有这个错误之后我就在网上到处找issue，我看都说electron要装32位的，还有什么agora_electron的配置里面要写arch：“ia32”这些。于是我就删了node_modules，然后在.npmrc里面加上了arch=ia32，在agora_electron写上了"agora_electron": {
"electron_version": "12.0.0",
"prebuilt": true,
"platform": "win32",
"arch": "ia32"
},
并且保证了electron装的是12.0.0
改了这些之后，我yarn安装，yarn start正常。我就又试了一遍yarn dist:win32和yarn dist:win64。结果这次相反，win-ia32-unpacked文件夹下的exe我点开正常了，win-unpacked文件夹下的反而又报那个错误。

我寻思项目代码我一开始原封不动下载下来，就执行yarn，yarn start，yarn dist:win64，yarn dist:win32，这几个命令，但是win32那个包就报错了。

**Comment by LichKing-2234** [comment]
yarn dist:win64 之前，需要修改agora_electron中的arch为x64并重新yarn
yarn dist:win32 之前，需要修改agora_electron中的arch为ia32并重新yarn

**Comment by denglouhen** [comment]
> yarn dist:win64 之前，需要修改agora_electron中的arch为x64并重新yarn yarn dist:win32 之前，需要修改agora_electron中的arch为ia32并重新yarn

好的谢谢大佬，那次在论坛也得知是不能同时打win32和win64的包。没事了
