### ISSUE TITLE
窗口共享

### ISSUE THREAD

**Issue by yi121320125** [AgoraIO/Electron-SDK#99]
sdk 版本 2.8.0-hotfix.1
Mac 窗口共享报错
videosourceStartScreenCaptureByWindow is not a function

sdk 版本 2.4.0-beta.2 是正常的

**Comment by yi121320125** [comment]
2.4.0 和 2.8.0 用法不一样

**Comment by plutoless** [comment]
videosource修改为videoSource了，原来的命名有些问题，CHANGELOG里应该有提
